### ISSUE TITLE
Entries should be paginated

### ISSUE THREAD

**Issue by tivac** [tivac/crucible#133]
Right now when you click into a schema anthracite grabs every single entry within that schema. It's nice and simple, but isn't going to scale long term.

- Entries should be paginated with some reasonable default number of items per page (50?).
- Paginating should update the URL so pages are deep-linkable
- ["Item Pagination"](https://developer.yahoo.com/ypatterns/navigation/pagination/item.html) is probably the right design pattern here.
- Behavior between details view and pagination is currently undefined, will need to be mulled over.

**Comment by kevinkace** [comment]
Small UX idea WRT items per page: a smaller number (20?) as to not always necessitate a scroll. This would only be beneficial if flipping through pages is an actual use case, (nice to just click through pages, rather than click, scroll; click, scroll). 

Should be reasonably easy to have the items fill the available space with flexbox/min-height, and certain details could be shown/hidden.

**Comment by tivac** [comment]
Agree w/ @kevinkace on the UX, if we stick w/ the current design that's absolutely how it should be structured.

I've been feeling like we should adopt a more keystone-like UI for a while, the current one never quite worked out how I had hoped it would.
