### ISSUE TITLE
Hidden fields get saved

### ISSUE THREAD

**Issue by Ryan-McMillan** [tivac/crucible#93]
When a field is hidden, the data is still saved off in firebase

**Comment by tivac** [comment]
It could be removed, but I'm not 100% sure that's actually a great experience. Still figuring that one out.

**Comment by ctcleary** [comment]
Was a decision ever made on the desired behavior for this issue?

**Comment by tivac** [comment]
I think leaving the info in the UI but clearing it from Firebase is probably the best user experience. It doesn't need to be persisted beyond that page though, if you refresh and it's gone that is fine. The thing I'm worried about it someone doing some work, checking a box they don't understand which hides those fields, and then losing all that work because we immediately cleared it.

Seem reasonable?
